# Generated by Django 4.2.5 on 2023-09-25 16:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDraw',
            fields=[
                ('luckydrawtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('luckydraw_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('draw_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LuckyDrawContext',
            fields=[
                ('context_id', models.AutoField(primary_key=True, serialize=False)),
                ('context_date', models.DateField()),
                ('context_luckynumber_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), blank=True, null=True, size=None)),
                ('is_winner_announced', models.BooleanField(default=False)),
                ('luckydrawtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luckydrawcontext_set', to='luckydraw.luckydraw')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('coupen_number', models.CharField(max_length=10)),
                ('coupen_type', models.CharField(choices=[('BLOCK', 'Block'), ('BOX', 'Box'), ('SUPER', 'Super')], max_length=50)),
                ('coupen_count', models.IntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('prize', models.CharField(choices=[('FIRST_PRIZE', 'First Prize'), ('SECOND_PRIZE', 'Second Prize'), ('THIRD_PRIZE', 'Third Prize'), ('FOURTH_PRIZE', 'Fourth Prize'), ('FIFTH_PRIZE', 'Fifth Prize')], max_length=50)),
                ('context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_set', to='luckydraw.luckydrawcontext')),
            ],
        ),
    ]
