# Generated by Django 4.2.5 on 2023-09-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDrawContext',
            fields=[
                ('context_id', models.AutoField(primary_key=True, serialize=False)),
                ('context_name', models.CharField(max_length=50)),
                ('context_date', models.DateField(auto_now=True)),
                ('context_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LuckyDrawType',
            fields=[
                ('luckydraw_id', models.AutoField(primary_key=True, serialize=False)),
                ('luckydraw_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('lucky_number', models.CharField(max_length=50, unique=True)),
                ('participant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_set', to='luckydraw.luckydrawcontext')),
            ],
        ),
        migrations.AddField(
            model_name='luckydrawcontext',
            name='luckydraw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luckydrawcontext_set', to='luckydraw.luckydrawtype'),
        ),
        migrations.CreateModel(
            name='ContextWinner',
            fields=[
                ('winner_id', models.AutoField(primary_key=True, serialize=False)),
                ('context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextwinner_set', to='luckydraw.luckydrawcontext')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextwinner_set', to='luckydraw.participants')),
            ],
        ),
    ]
