# Generated by Django 4.2.5 on 2023-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='prize',
            field=models.CharField(blank=True, choices=[('FIRST_PRIZE', 'First Prize'), ('SECOND_PRIZE', 'Second Prize'), ('THIRD_PRIZE', 'Third Prize'), ('FOURTH_PRIZE', 'Fourth Prize'), ('FIFTH_PRIZE', 'Fifth Prize')], max_length=50, null=True),
        ),
    ]
