# Generated by Django 4.2.5 on 2023-09-23 04:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawcontext',
            name='context_luckynumber_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), blank=True, null=True, size=None),
        ),
    ]
