# Generated by Django 4.2.5 on 2023-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0002_alter_participants_coupen_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawcontext',
            name='count_limit',
            field=models.IntegerField(default=20),
        ),
    ]
