# Generated by Django 4.2.5 on 2023-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0002_alter_luckydrawcontext_context_luckynumber_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawcontext',
            name='context_date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
