# Generated by Django 4.2.5 on 2024-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0003_luckydrawcontext_count_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'ordering': ['-participant_id']},
        ),
    ]
