# Generated by Django 4.2.5 on 2023-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0004_alter_luckydrawcontext_context_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawcontext',
            name='context_date',
            field=models.DateField(unique=True),
        ),
    ]
