# Generated by Django 4.2.5 on 2023-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0005_alter_luckydrawcontext_context_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawcontext',
            name='is_winner_announced',
            field=models.BooleanField(default=False),
        ),
    ]
