# Generated by Django 4.2.5 on 2023-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0006_luckydrawcontext_is_winner_announced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawcontext',
            name='context_date',
            field=models.DateField(),
        ),
    ]
